apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: abhishreep/nodeapp:latest
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
             cpu: 600m
             memory: 100Mi
      
             